package config

import (
	"context"
	"maps"
	"strings"

	"github.com/newstack-cloud/bluelink/libs/blueprint/linktypes"
	"github.com/newstack-cloud/bluelink/libs/blueprint/schema"
	"github.com/newstack-cloud/bluelink/libs/plugin-framework/sdk/transformutils"
)

type ResolvedConfig struct {
	Name      string
	StoreName string
	Resource  *schema.Resource
	// HandlerSelectorLabels is the subset of the config's labels matched by
	// inbound handler -> config link edges. Only these labels are propagated onto
	// the emitted concrete store (see infraMeta for why the full label set is
	// deliberately not carried over).
	HandlerSelectorLabels map[string]string
}

func (c *ResolvedConfig) ResourceName() string {
	return c.Name
}

func (c *ResolvedConfig) ResourceType() string {
	return "celerity/config"
}

func resolveConfig(
	_ context.Context,
	_ *transformutils.Run,
	name string,
	resource *schema.Resource,
	linkGraph linktypes.DeclaredLinkGraph,
	_ *schema.Blueprint,
) (transformutils.ResolvedResource, error) {
	return &ResolvedConfig{
		Name:                  name,
		StoreName:             storeNameFor(name, resource.Spec),
		Resource:              resource,
		HandlerSelectorLabels: handlerSelectorLabels(name, linkGraph),
	}, nil
}

// Collects the labels that inbound handler -> config edges matched: the labels
// the emitted concrete store must carry for the linked handlers' preserved
// lambda linkSelectors to re-match it and form the concrete
// lambda -> store link.
func handlerSelectorLabels(
	name string,
	linkGraph linktypes.DeclaredLinkGraph,
) map[string]string {
	labels := map[string]string{}
	if linkGraph == nil {
		return labels
	}
	for _, edge := range linkGraph.EdgesTo(name) {
		if edge.SourceType != "celerity/handler" {
			continue
		}
		maps.Copy(labels, labelsFromSelectorKeys(edge.SelectorKeys))
	}
	return labels
}

// Parses selector keys of the form "label::<key>:<value>"
// (as generated by the blueprint selector grouping) into a label map.
func labelsFromSelectorKeys(keys []string) map[string]string {
	labels := map[string]string{}
	for _, key := range keys {
		trimmed := strings.TrimPrefix(key, "label::")
		if trimmed == key {
			continue
		}
		name, value, ok := strings.Cut(trimmed, ":")
		if !ok || name == "" {
			continue
		}
		labels[name] = value
	}
	return labels
}
