package queue

import (
	"context"
	"strings"

	"github.com/newstack-cloud/bluelink/libs/blueprint/linktypes"
	"github.com/newstack-cloud/bluelink/libs/blueprint/schema"
	"github.com/newstack-cloud/bluelink/libs/plugin-framework/sdk/transformutils"
)

// TopicForwardEdge captures a resolved celerity/queue -> celerity/topic edge: the
// queue's messages are forwarded to the topic by an intermediary Lambda emitted on
// aws-serverless.
type TopicForwardEdge struct {
	// TopicName is the abstract topic resource name the queue forwards to.
	TopicName string
	// SelectorLabels are the topic labels the queue's link selector matched,
	// reconstructed from the edge's selector keys. The emitted forwarder function
	// carries these as its own link selector so the function::sns link resolves it
	// to the concrete topic.
	SelectorLabels map[string]string
}

// ResolvedQueue carries the abstract queue through to the emit phase. Beyond the
// queue's own metadata (labels + linkSelector are preserved as-is), it records any
// outbound celerity/topic forwarding edges so the emit can provision the
// intermediary forwarder.
type ResolvedQueue struct {
	Name          string
	Resource      *schema.Resource
	TopicForwards []*TopicForwardEdge
}

func (q *ResolvedQueue) ResourceName() string {
	return q.Name
}

func (q *ResolvedQueue) ResourceType() string {
	return "celerity/queue"
}

func resolveQueue(
	_ context.Context,
	_ *transformutils.Run,
	name string,
	resource *schema.Resource,
	linkGraph linktypes.DeclaredLinkGraph,
	_ *schema.Blueprint,
) (transformutils.ResolvedResource, error) {
	return &ResolvedQueue{
		Name:          name,
		Resource:      resource,
		TopicForwards: topicForwardEdges(name, linkGraph),
	}, nil
}

// topicForwardEdges collects the queue's outbound celerity/topic edges from the
// declared link graph, parsing each edge's selector keys into the topic labels the
// forwarder must carry.
func topicForwardEdges(name string, linkGraph linktypes.DeclaredLinkGraph) []*TopicForwardEdge {
	if linkGraph == nil {
		return nil
	}
	var edges []*TopicForwardEdge
	for _, edge := range linkGraph.EdgesFrom(name) {
		if edge == nil || edge.TargetType != "celerity/topic" {
			continue
		}
		edges = append(edges, &TopicForwardEdge{
			TopicName:      edge.Target,
			SelectorLabels: labelsFromSelectorKeys(edge.SelectorKeys),
		})
	}
	return edges
}

// labelsFromSelectorKeys parses selector keys of the form "label::<key>:<value>"
// (as generated by the blueprint selector grouping) into a label map.
func labelsFromSelectorKeys(keys []string) map[string]string {
	labels := map[string]string{}
	for _, key := range keys {
		trimmed := strings.TrimPrefix(key, "label::")
		if trimmed == key {
			continue
		}
		name, value, ok := strings.Cut(trimmed, ":")
		if !ok || name == "" {
			continue
		}
		labels[name] = value
	}
	return labels
}
