package queue

import (
	"context"
	"strings"

	"github.com/newstack-cloud/bluelink/libs/blueprint/linktypes"
	"github.com/newstack-cloud/bluelink/libs/blueprint/schema"
	"github.com/newstack-cloud/bluelink/libs/plugin-framework/sdk/transformutils"
)

// TopicForwardEdge captures a resolved celerity/queue -> celerity/topic edge: the
// queue's messages are forwarded to the topic by an intermediary Lambda emitted on
// aws-serverless.
type TopicForwardEdge struct {
	// TopicName is the abstract topic resource name the queue forwards to.
	TopicName string
	// SelectorLabels are the topic labels the queue's link selector matched,
	// reconstructed from the edge's selector keys. The emitted forwarder function
	// carries these as its own link selector so the function::sns link resolves it
	// to the concrete topic.
	SelectorLabels map[string]string
}

// ResolvedQueue carries the abstract queue through to the emit phase. Beyond the
// queue's own metadata (labels + linkSelector are preserved as-is), it records any
// outbound celerity/topic forwarding edges so the emit can provision the
// intermediary forwarder, and whether the queue is also consumed (which competes
// with forwarding for the queue's messages).
type ResolvedQueue struct {
	Name          string
	Resource      *schema.Resource
	TopicForwards []*TopicForwardEdge
	// Consumed is true when a celerity/consumer links to this queue. A consumed
	// queue's handler polls it via an SQS event source mapping, which competes with
	// the forwarder's mapping (SQS is competing-consumers, not fan-out), so a queue
	// cannot be both consumed and forwarded on aws-serverless.
	Consumed bool
}

func (q *ResolvedQueue) ResourceName() string {
	return q.Name
}

func (q *ResolvedQueue) ResourceType() string {
	return "celerity/queue"
}

func resolveQueue(
	_ context.Context,
	_ *transformutils.Run,
	name string,
	resource *schema.Resource,
	linkGraph linktypes.DeclaredLinkGraph,
	_ *schema.Blueprint,
) (transformutils.ResolvedResource, error) {
	forwards, consumed := outboundEdges(name, linkGraph)
	return &ResolvedQueue{
		Name:          name,
		Resource:      resource,
		TopicForwards: forwards,
		Consumed:      consumed,
	}, nil
}

// outboundEdges collects the queue's outbound celerity/topic forwarding edges from
// the declared link graph (parsing each edge's selector keys into the topic labels
// the forwarder must carry) and reports whether the queue is also consumed (has an
// outbound celerity/consumer edge).
func outboundEdges(name string, linkGraph linktypes.DeclaredLinkGraph) ([]*TopicForwardEdge, bool) {
	if linkGraph == nil {
		return nil, false
	}
	var forwards []*TopicForwardEdge
	consumed := false
	for _, edge := range linkGraph.EdgesFrom(name) {
		if edge == nil {
			continue
		}
		switch edge.TargetType {
		case "celerity/topic":
			forwards = append(forwards, &TopicForwardEdge{
				TopicName:      edge.Target,
				SelectorLabels: labelsFromSelectorKeys(edge.SelectorKeys),
			})
		case "celerity/consumer":
			consumed = true
		}
	}
	return forwards, consumed
}

// labelsFromSelectorKeys parses selector keys of the form "label::<key>:<value>"
// (as generated by the blueprint selector grouping) into a label map.
func labelsFromSelectorKeys(keys []string) map[string]string {
	labels := map[string]string{}
	for _, key := range keys {
		trimmed := strings.TrimPrefix(key, "label::")
		if trimmed == key {
			continue
		}
		name, value, ok := strings.Cut(trimmed, ":")
		if !ok || name == "" {
			continue
		}
		labels[name] = value
	}
	return labels
}
